name: my workflow
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [test]
    if:
      contains('
        CashBackHacker1.1/tree/main
        CashBackHacker1.1/tree/TestNG
        CashBackHacker1.1/tree/JUnit4
      ', github.ref)

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test


